name: Build and Upload Artifact
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Package the extension
      run: npx vsce package

    - name: Upload VSIX to workflow run's assets
      uses: actions/upload-artifact@v3
      with:
        name: titlebar-colour.vsix
        path: ./titlebar-colour-*.vsix
